name: Instagram Watcher

on:
  schedule:
    - cron: "*/120 * * * *"    # toutes les 5 minutes
  workflow_dispatch:         # pour tester manuellement

jobs:
  check_instagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          OUTLOOK_EMAIL: ${{ secrets.OUTLOOK_EMAIL }}
          OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          FREE_USER: ${{ secrets.FREE_USER }}
          FREE_KEY: ${{ secrets.FREE_KEY }}
        run: python insta_alert.py
